### ISSUE TITLE
Process 3SAT problems in CNF form 

### ISSUE THREAD

**Issue by souravsanyal06** [jtiosue/qubovert#33]
Hello

Is there any interface where a 3SAT problem in a DIMACS CNF file format can be read from a file and automatically be parsed in PCBO().add_constraint ? 

for example, can a CNF formula (x0 or x1 or  ~x2)(x1 or x2 or x3) be represented as [0,1,-2][1,2,3] ?

**Comment by jtiosue** [comment]
Sorry for the late reply! That is a great suggestion, and it is now on my to do list.
