### ISSUE TITLE
Suspected bug in subgraph()

### ISSUE THREAD

**Issue by gilirosenberg** [jtiosue/qubovert#38]
I think I've found a bug in `subgraph()`. Here's a minimal reproducer:
```python
from qubovert.utils import subgraph
import numpy as np

G = {(2,): 1, (2, 3): -1}
connections={3: 1}
qubo = subgraph(G, [2], connections)
print(qubo)
```
The output I get is:
```python
{(2,): 1.0}
```
Whereas the output I expect is:
```python
{}
```

I suspect the issue is [at the end of `subgraph()`](https://github.com/jtiosue/qubovert/blob/d5ea46349d2a058954fb2cb06f559c0d3fb382c5/qubovert/utils/_subgraph.py#L91), where we have:
```python
        if value:
            D[key] = value
```
which I think should be changed to something like this:
```python
        if value:
            D[key] = value
        else:
            try:
                del D[key]
            except KeyError:
                pass
```
To deal with the situation in which substituting the values from `connections` causes `value` to be zero. I've assumed here that it is possible that `key` is not in `D`, since I see that just above there is `D.get(key, 0)` which was designed to work in that scenario. But if that's impossible then we could get rid of the try/except.

**Comment by gilirosenberg** [comment]
Oh, and based on a cursory look, it's possible that `subvalue()` is suffering from a similar issue.

**Comment by jtiosue** [comment]
Nice catch! This was indeed an error. It is now fixed in the dev branch, and will be merged to master soon. Thanks so much for finding this!

**Comment by gilirosenberg** [comment]
Thanks for the fix @jtiosue!

**Comment by jtiosue** [comment]
@gilirosenberg12 Yes sorry for the long delay! It is merged to master and uploaded to pip. `pip install --upgrade qubovert` should do the trick :)

**Comment by gilirosenberg** [comment]
Thanks for the fix!
