### ISSUE TITLE
TypeError: loop of ufunc does not support argument 0 of type Float which has no callable log10 method

### ISSUE THREAD

**Issue by AjayKumar-LVLS** [jtiosue/qubovert#41]
Error obtained in the line:
res = qv.sim.anneal_qubo(Q, num_anneals=1000)

parameter Q that is being passed is:

{(0, 0): -6,
 (0, 54): 12,
 (0, 57): 12,
 (0, 60): 12,
 (1, 1): -6,
 (1, 55): 12,
 (1, 58): 12,
 (1, 61): 12,
 (2, 2): -6,
 (2, 56): 12,
 (2, 59): 12,
 (2, 62): 12,
 (3, 3): -73,
 (3, 4): 48,
 (3, 5): 12,
 (3, 6): 24,
 (3, 7): 12,
 (3, 8): 24,
 (3, 27): 12,
 (3, 45): 12,
 (3, 46): 24,
 (3, 47): 48,
 (3, 54): -24,
 (4, 4): -122,
 (4, 5): 24,
 (4, 6): 48,
 (4, 7): 24,
 (4, 8): 48,
 (4, 27): 24,
 (4, 45): 24,
 (4, 46): 48,
 (4, 47): 96,
 (4, 54): -48,
 (5, 5): -73,
 (5, 6): 48,
 (5, 7): 12,
 (5, 8): 24,
 (5, 28): 12,
 (5, 45): 12,
 (5, 46): 24,
 (5, 47): 48,
 (5, 55): -24,
 (6, 6): -122,
 (6, 7): 24,
 (6, 8): 48,
 (6, 28): 24,
 (6, 45): 24,
 (6, 46): 48,
 (6, 47): 96,
 (6, 55): -48,
 (7, 7): -73,
 (7, 8): 48,
 (7, 29): 12,
 (7, 45): 12,
 (7, 46): 24,
 (7, 47): 48,
 (7, 56): -24,
 (8, 8): -122,
 (8, 29): 24,
 (8, 45): 24,
 (8, 46): 48,
 (8, 47): 96,
 (8, 56): -48,
 (9, 9): -73,
 (9, 10): 48,
 (9, 11): 96,
 (9, 12): 12,
 (9, 13): 24,
 (9, 14): 48,
 (9, 15): 12,
 (9, 16): 24,
 (9, 17): 48,
 (9, 30): 12,
 (9, 31): 24,
 (9, 48): 12,
 (9, 49): 24,
 (9, 50): 48,
 (9, 57): -48,
 (10, 10): -122,
 (10, 11): 192,
 (10, 12): 24,
 (10, 13): 48,
 (10, 14): 96,
 (10, 15): 24,
 (10, 16): 48,
 (10, 17): 96,
 (10, 30): 24,
 (10, 31): 48,
 (10, 48): 24,
 (10, 49): 48,
 (10, 50): 96,
 (10, 57): -96,
 (11, 11): -148,
 (11, 12): 48,
 (11, 13): 96,
 (11, 14): 192,
 (11, 15): 48,
 (11, 16): 96,
 (11, 17): 192,
 (11, 30): 48,
 (11, 31): 96,
 (11, 48): 48,
 (11, 49): 96,
 (11, 50): 192,
 (11, 57): -192,
 (12, 12): -73,
 (12, 13): 48,
 (12, 14): 96,
 (12, 15): 12,
 (12, 16): 24,
 (12, 17): 48,
 (12, 32): 12,
 (12, 33): 24,
 (12, 48): 12,
 (12, 49): 24,
 (12, 50): 48,
 (12, 58): -48,
 (13, 13): -122,
 (13, 14): 192,
 (13, 15): 24,
 (13, 16): 48,
 (13, 17): 96,
 (13, 32): 24,
 (13, 33): 48,
 (13, 48): 24,
 (13, 49): 48,
 (13, 50): 96,
 (13, 58): -96,
 (14, 14): -148,
 (14, 15): 48,
 (14, 16): 96,
 (14, 17): 192,
 (14, 32): 48,
 (14, 33): 96,
 (14, 48): 48,
 (14, 49): 96,
 (14, 50): 192,
 (14, 58): -192,
 (15, 15): -73,
 (15, 16): 48,
 (15, 17): 96,
 (15, 34): 12,
 (15, 35): 24,
 (15, 48): 12,
 (15, 49): 24,
 (15, 50): 48,
 (15, 59): -48,
 (16, 16): -122,
 (16, 17): 192,
 (16, 34): 24,
 (16, 35): 48,
 (16, 48): 24,
 (16, 49): 48,
 (16, 50): 96,
 (16, 59): -96,
 (17, 17): -148,
 (17, 34): 48,
 (17, 35): 96,
 (17, 48): 48,
 (17, 49): 96,
 (17, 50): 192,
 (17, 59): -192,
 (18, 18): -73,
 (18, 19): 48,
 (18, 20): 96,
 (18, 21): 12,
 (18, 22): 24,
 (18, 23): 48,
 (18, 24): 12,
 (18, 25): 24,
 (18, 26): 48,
 (18, 36): 12,
 (18, 37): 24,
 (18, 38): 48,
 (18, 51): 12,
 (18, 52): 24,
 (18, 53): 48,
 (18, 60): -60,
 (19, 19): -122,
 (19, 20): 192,
 (19, 21): 24,
 (19, 22): 48,
 (19, 23): 96,
 (19, 24): 24,
 (19, 25): 48,
 (19, 26): 96,
 (19, 36): 24,
 (19, 37): 48,
 (19, 38): 96,
 (19, 51): 24,
 (19, 52): 48,
 (19, 53): 96,
 (19, 60): -120,
 (20, 20): -148,
 (20, 21): 48,
 (20, 22): 96,
 (20, 23): 192,
 (20, 24): 48,
 (20, 25): 96,
 (20, 26): 192,
 (20, 36): 48,
 (20, 37): 96,
 (20, 38): 192,
 (20, 51): 48,
 (20, 52): 96,
 (20, 53): 192,
 (20, 60): -240,
 (21, 21): -73,
 (21, 22): 48,
 (21, 23): 96,
 (21, 24): 12,
 (21, 25): 24,
 (21, 26): 48,
 (21, 39): 12,
 (21, 40): 24,
 (21, 41): 48,
 (21, 51): 12,
 (21, 52): 24,
 (21, 53): 48,
 (21, 61): -60,
 (22, 22): -122,
 (22, 23): 192,
 (22, 24): 24,
 (22, 25): 48,
 (22, 26): 96,
 (22, 39): 24,
 (22, 40): 48,
 (22, 41): 96,
 (22, 51): 24,
 (22, 52): 48,
 (22, 53): 96,
 (22, 61): -120,
 (23, 23): -148,
 (23, 24): 48,
 (23, 25): 96,
 (23, 26): 192,
 (23, 39): 48,
 (23, 40): 96,
 (23, 41): 192,
 (23, 51): 48,
 (23, 52): 96,
 (23, 53): 192,
 (23, 61): -240,
 (24, 24): -73,
 (24, 25): 48,
 (24, 26): 96,
 (24, 42): 12,
 (24, 43): 24,
 (24, 44): 48,
 (24, 51): 12,
 (24, 52): 24,
 (24, 53): 48,
 (24, 62): -60,
 (25, 25): -122,
 (25, 26): 192,
 (25, 42): 24,
 (25, 43): 48,
 (25, 44): 96,
 (25, 51): 24,
 (25, 52): 48,
 (25, 53): 96,
 (25, 62): -120,
 (26, 26): -148,
 (26, 42): 48,
 (26, 43): 96,
 (26, 44): 192,
 (26, 51): 48,
 (26, 52): 96,
 (26, 53): 192,
 (26, 62): -240,
 (27, 27): 6,
 (27, 54): -24,
 (28, 28): 6,
 (28, 55): -24,
 (29, 29): 6,
 (29, 56): -24,
 (30, 30): 6,
 (30, 31): 24,
 (30, 57): -48,
 (31, 31): 24,
 (31, 57): -96,
 (32, 32): 6,
 (32, 33): 24,
 (32, 58): -48,
 (33, 33): 24,
 (33, 58): -96,
 (34, 34): 6,
 (34, 35): 24,
 (34, 59): -48,
 (35, 35): 24,
 (35, 59): -96,
 (36, 36): 6,
 (36, 37): 24,
 (36, 38): 48,
 (36, 60): -60,
 (37, 37): 24,
 (37, 38): 96,
 (37, 60): -120,
 (38, 38): 96,
 (38, 60): -240,
 (39, 39): 6,
 (39, 40): 24,
 (39, 41): 48,
 (39, 61): -60,
 (40, 40): 24,
 (40, 41): 96,
 (40, 61): -120,
 (41, 41): 96,
 (41, 61): -240,
 (42, 42): 6,
 (42, 43): 24,
 (42, 44): 48,
 (42, 62): -60,
 (43, 43): 24,
 (43, 44): 96,
 (43, 62): -120,
 (44, 44): 96,
 (44, 62): -240,
 (45, 45): -78,
 (45, 46): 24,
 (45, 47): 48,
 (46, 46): -144,
 (46, 47): 96,
 (47, 47): -240,
 (48, 48): -78,
 (48, 49): 24,
 (48, 50): 48,
 (49, 49): -144,
 (49, 50): 96,
 (50, 50): -240,
 (51, 51): -78,
 (51, 52): 24,
 (51, 53): 48,
 (52, 52): -144,
 (52, 53): 96,
 (53, 53): -240,
 (54, 54): 18,
 (54, 57): 12,
 (54, 60): 12,
 (55, 55): 18,
 (55, 58): 12,
 (55, 61): 12,
 (56, 56): 18,
 (56, 59): 12,
 (56, 62): 12,
 (57, 57): 90,
 (57, 60): 12,
 (58, 58): 90,
 (58, 61): 12,
 (59, 59): 90,
 (59, 62): 12,
 (60, 60): 144,
 (61, 61): 144,
 (62, 62): 144}

Any help here is appreciated.

**Comment by jtiosue** [comment]
Hi, setting `Q` equal to what you have written and running `qubovert.sim.anneal_qubo(Q, num_anneals=1000)` works for me with no error. Are you sure the error is occurring on the qubovert end? Please try upgrading qubovert with `pip install --upgrade qubovert``, and then post here a minimal code block that reproduces the error.
