### ISSUE TITLE
Extending DictArithmetic to include vector  non_zero_min??

### ISSUE THREAD

**Issue by strelzoff-erdc** [jtiosue/qubovert#43]
Hiya,

  I have a constrained binary optimization which involved site selection based on a distance matrix.  

- my space is
    - X = vector of binary decision variables
    - site in solution?
- and my objective is of the form
    -  model = sum(non_zero_min(dist_matrix @ X[i] , axis=1) ) 
    -  sum of travel to each nearest site in solution
- with constraint
   -   model.add_constraint_eq _zero(sum(x.values()) - num_selected_sites ,lam=10)
   - limited number of sites

The space is very large so Gurobi and other exact solvers fail on the hardware we have available.  So, heuristics are the only way forward.

I could extend the DictArithmetic class to include "non_zero_min" but would this work.  Or, is there and easier way forward that I'm not seeing.

thanks

**Comment by jtiosue** [comment]
Sorry I don't think I fully understand. What is the issue? It seems like everything works as is here. (One suggestion though, for large problems, instead of using `sum(non_zero_min(...))`, you can speed it up a lot by using `qubovert.utils.sum(non_zero_min(...))`)

**Comment by jtiosue** [comment]
Please let me know if there is anything else, otherwise I will close this issue.
