### ISSUE TITLE
Dealing with "force fields"

### ISSUE THREAD

**Issue by Annarchia** [jtiosue/qubovert#47]
I'm working on a PUBO encoding for polymer lattice models and I need a way to include interactions between nearest-neighbour monomers. The Hamiltonian to be minimised takes the form

$$ H_{targer} = \sum_E \sum_{i=1}^D \sum_{j=1}^D (1-e^E) q_i^{E-} q_j^{E+} \epsilon_{ij} $$

Where $e^E=1$ if the E-th edge is active, in which case I don't count the interaction (because the monomers are bounded). $q_i^{E-}, q_j^{E+}$ indicate which monomers sit at the sides of the edge. $D$ is the number of monomer species. $\epsilon_{ij}$ is the interaction coefficient between a monomer of type i and type j.
In the HP model, $\epsilon = \begin{pmatrix} -1&0 \\ 0&0 \end{pmatrix}$.
Now, I'm trying to translate this formula into code, but I'm having trouble accounting for the interaction coefficients.
I came up with the following
`H_t = sum(sum(sum((1-e[E])*qi[pm[E][0]+i]*qi[pm[E][1]+j]*epsilon[D*i+j] for j in range(D)) for i in range(D)) for E in range(edges))`

The problem is that by using this, the $\epsilon_{ij}$ coefficients become part of my state and I don't want that.
Thanks for the help

**Comment by jtiosue** [comment]
Hi, I don't think I understand your notation. For example, you said that epsilon is a 2 by 2 matrix -1&0, 0&0, but in the Hamiltonian the indices i and j of epsilon run from 1 to D.  Further, when you say that $q_i^{E-},q_i^{E+}$ denote which monomers sit at the sides of the edges, do you mean that they are the boolean variables? I don't understand what you mean by not wanting the epsilon coefficients to become part of your state. As they are necessary to specify the problem, I don't understand how they could not become part of your state. Please try to reduce your question to the _minimal_ amount of information needed to reproduce the issue.

**Comment by jtiosue** [comment]
@Annarchia Please let me know if there is anything else here, otherwise I will close this issue, thanks!
